export default {
  THEMES: {
    shift: {
        type: 'uChat Light',
        sidebarBg: '#282727',
        sidebarText: '#fff',
        sidebarUnreadText: '#fff',
        sidebarTextHoverBg: '#494949',
        sidebarTextActiveBorder: '#11939a',
        sidebarTextActiveColor: '#FFFFFF',
        sidebarHeaderBg: '#000000',
        sidebarHeaderTextColor: '#FFFFFF',
        onlineIndicator: '#629a41',
        awayIndicator: '#ecab20',
        mentionBj: '#f8f8f9',
        mentionColor: '#11939a',
        centerChannelBg: '#ffffff',
        centerChannelColor: '#333333',
        newMessageSeparator: '#11939a',
        linkColor: '#11939a',
        buttonBg: '#11939a',
        buttonColor: '#FFFFFF',
        mentionHighlightBg: '#e8fafa',
        mentionHighlightLink: '#11939a',
        codeTheme: 'github',
    },
    monokai: {
        type: 'uChat Dark',
        sidebarBg: '#282727',
        sidebarText: '#fff',
        sidebarUnreadText: '#fff',
        sidebarTextHoverBg: '#494949',
        sidebarTextActiveBorder: '#11939a',
        sidebarTextActiveColor: '#FFFFFF',
        sidebarHeaderBg: '#000000',
        sidebarHeaderTextColor: '#FFFFFF',
        onlineIndicator: '#629a41',
        awayIndicator: '#ecab20',
        mentionBj: '#f8f8f9',
        mentionColor: '#11939a',
        centerChannelBg: '#282727',
        centerChannelColor: '#ffffff',
        newMessageSeparator: '#11939a',
        linkColor: '#11939a',
        buttonBg: '#11939a',
        buttonColor: '#FFFFFF',
        mentionHighlightBg: '#11939a',
        mentionHighlightLink: '#FFFFFF',
        codeTheme: 'monokai',
    },
  }
};
